version: "3.9"


volumes:
  postgres-data:
    external: true   
services:
  db:
    build:
      context: ./relational-data
      dockerfile: ./Dockerfile.dev
    volumes:
        - postgres-data:/var/lib/postgresql/data
    environment:
        - POSTGRES_MULTIPLE_DATABASES=users,workouts
        - POSTGRES_PASSWORD=test-databases
    ports:
        - 15432:5432
  workouts:
    build:
      context: ./workouts
      dockerfile: ./Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./workouts:/app
    environment:
      DATABASE_URL: postgresql://workouts:password@postgres/workouts
      WAIT_HOSTS: postgres:5432
  accounts:
    build:
      context: ./accounts
      dockerfile: ./Dockerfile.dev
    ports:
      - "8001:8000"
    volumes:
      - ./accounts:/app 
    environment:
      DATABASE_URL: postgresql://accounts:password@postgres/accounts
      WAIT_HOSTS: postgres:5432
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
        - ./ghi:/app
    ports:
        - "3000:3000"
    environment:
        HOST_OS: ${OS}
        NODE_ENV: development
        HOST: "0.0.0.0"
        REACT_APP_USERS: http://localhost:8000
        REACT_APP_WORKOUTS: http://localhost:8001

